//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATHANG
    {
        public string MADH { get; set; }
        public string MAMATHANG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public int MACTDH { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
        public virtual DATHANG DATHANG { get; set; }
    }
}
