//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE
    {
        public int MATHONGKE { get; set; }
        public Nullable<System.DateTime> NGAYTHONGKE { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string MASPBANCHAY { get; set; }
        public string SANPHAMBANCHAY { get; set; }
        public Nullable<int> SOLUONGBANRA { get; set; }
        public Nullable<int> SOLUONGBANCHAY { get; set; }
    }
}
