//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DIADIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIADIEM()
        {
            this.DATHANGs = new HashSet<DATHANG>();
        }
    
        public int MADIADIEM { get; set; }
       
        public Nullable<int> MAKHACHHANG { get; set; } 
        [Required(ErrorMessage = "Please enter TENDIACHI")]
        public string TENDIACHI { get; set; }
        [RegularExpression(@"^\d{10,}$", ErrorMessage = "Phone number must be at least 10 digits")]
        public string SDT { get; set; }

        public Nullable<bool> MACDINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
