//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.HINHANHs = new HashSet<HINHANH>();
        }
    
        public string MAMATHANG { get; set; }
        public string TENHANG { get; set; }
        public string ANHSANPHAM { get; set; }
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        public string TENHANGSANXUAT { get; set; }
        public Nullable<double> GIAHANG { get; set; }
        public string BAOHANH { get; set; }
        public string LOAI { get; set; }
        public Nullable<int> KICHTHUOC { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<int> MASALE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        public virtual SALE SALE { get; set; }
    }
}
