//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int MANOTIFICATION { get; set; }
        public Nullable<int> SENDID { get; set; }
        public string EMAIL { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string MADH { get; set; }
        public string TENKH { get; set; }
        public string AVATAR { get; set; }
        public string TENCHUCNANG { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
