//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAIGIAOHANG
    {
        public int MAVANDON { get; set; }
        public string VITRI { get; set; }
        public Nullable<System.DateTime> THOIGIANGIAOHANG { get; set; }
        public Nullable<System.DateTime> THOIGIANNHANHANG { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    }
}
